// Code generated by protoc-gen-go. DO NOT EDIT.
// source: servant_cluster.proto

package proto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_d975c2f921663dbb, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type TicketInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TicketInfo) Reset()         { *m = TicketInfo{} }
func (m *TicketInfo) String() string { return proto.CompactTextString(m) }
func (*TicketInfo) ProtoMessage()    {}
func (*TicketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d975c2f921663dbb, []int{1}
}

func (m *TicketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketInfo.Unmarshal(m, b)
}
func (m *TicketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketInfo.Marshal(b, m, deterministic)
}
func (m *TicketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketInfo.Merge(m, src)
}
func (m *TicketInfo) XXX_Size() int {
	return xxx_messageInfo_TicketInfo.Size(m)
}
func (m *TicketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TicketInfo proto.InternalMessageInfo

func (m *TicketInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TicketInfo) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *TicketInfo) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type TicketsInfo struct {
	TicketsInfo          []*TicketInfo `protobuf:"bytes,1,rep,name=tickets_info,json=ticketsInfo,proto3" json:"tickets_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TicketsInfo) Reset()         { *m = TicketsInfo{} }
func (m *TicketsInfo) String() string { return proto.CompactTextString(m) }
func (*TicketsInfo) ProtoMessage()    {}
func (*TicketsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d975c2f921663dbb, []int{2}
}

func (m *TicketsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketsInfo.Unmarshal(m, b)
}
func (m *TicketsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketsInfo.Marshal(b, m, deterministic)
}
func (m *TicketsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketsInfo.Merge(m, src)
}
func (m *TicketsInfo) XXX_Size() int {
	return xxx_messageInfo_TicketsInfo.Size(m)
}
func (m *TicketsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TicketsInfo proto.InternalMessageInfo

func (m *TicketsInfo) GetTicketsInfo() []*TicketInfo {
	if m != nil {
		return m.TicketsInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*TicketInfo)(nil), "proto.TicketInfo")
	proto.RegisterType((*TicketsInfo)(nil), "proto.TicketsInfo")
}

func init() { proto.RegisterFile("servant_cluster.proto", fileDescriptor_d975c2f921663dbb) }

var fileDescriptor_d975c2f921663dbb = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xcf, 0x41, 0x4b, 0x04, 0x21,
	0x14, 0x07, 0xf0, 0x75, 0xb6, 0x69, 0xe9, 0xcd, 0x10, 0xf5, 0x20, 0x90, 0x3d, 0x89, 0x27, 0x4f,
	0x4b, 0x6c, 0x7d, 0x83, 0x8a, 0xa8, 0xa3, 0x75, 0x5f, 0x36, 0xd7, 0x25, 0xa9, 0x54, 0xf4, 0xb5,
	0xb0, 0xdf, 0x3e, 0xd2, 0x89, 0x61, 0xa0, 0x93, 0xfe, 0xd1, 0xff, 0x4f, 0x1f, 0x5c, 0x65, 0x9b,
	0x0e, 0x5b, 0x4f, 0x1b, 0xf3, 0xf9, 0x9d, 0xc9, 0xa6, 0x55, 0x4c, 0x81, 0x02, 0xb6, 0x65, 0x91,
	0x0b, 0x68, 0x1f, 0xbe, 0x22, 0x1d, 0xe5, 0x33, 0xc0, 0xab, 0x33, 0x1f, 0x96, 0x9e, 0xfc, 0x3e,
	0xe0, 0x39, 0x34, 0x6e, 0xc7, 0x99, 0x60, 0xea, 0x4c, 0x37, 0x6e, 0x87, 0x08, 0x27, 0x74, 0x8c,
	0x96, 0x37, 0x82, 0xa9, 0x56, 0x97, 0x3d, 0x72, 0x58, 0x98, 0xe0, 0xc9, 0x7a, 0xe2, 0x73, 0xc1,
	0x54, 0xaf, 0xff, 0xa2, 0xbc, 0x83, 0xae, 0x5a, 0xb9, 0x60, 0xb7, 0xd0, 0x53, 0x8d, 0x1b, 0xe7,
	0xf7, 0x81, 0x33, 0x31, 0x57, 0xdd, 0xfa, 0xb2, 0x7e, 0x64, 0x35, 0xbe, 0xaa, 0x3b, 0x1a, 0x5b,
	0xeb, 0x03, 0x5c, 0xd4, 0xa3, 0x7b, 0x97, 0xe3, 0x96, 0xcc, 0xbb, 0x4d, 0x78, 0x0d, 0xf0, 0x68,
	0x69, 0xb0, 0xb1, 0x1f, 0x84, 0x32, 0xc0, 0x12, 0x27, 0x5e, 0x31, 0xe4, 0xec, 0xb7, 0xf1, 0x32,
	0x36, 0xfe, 0xb9, 0xb3, 0x9c, 0x28, 0x72, 0xf6, 0x76, 0x5a, 0xe2, 0xcd, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf9, 0x7b, 0x91, 0xc4, 0x38, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TicketDispatcherClient is the client API for TicketDispatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TicketDispatcherClient interface {
	GetTickets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TicketsInfo, error)
	SetTickets(ctx context.Context, in *TicketsInfo, opts ...grpc.CallOption) (*Empty, error)
}

type ticketDispatcherClient struct {
	cc *grpc.ClientConn
}

func NewTicketDispatcherClient(cc *grpc.ClientConn) TicketDispatcherClient {
	return &ticketDispatcherClient{cc}
}

func (c *ticketDispatcherClient) GetTickets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TicketsInfo, error) {
	out := new(TicketsInfo)
	err := c.cc.Invoke(ctx, "/proto.TicketDispatcher/GetTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketDispatcherClient) SetTickets(ctx context.Context, in *TicketsInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.TicketDispatcher/SetTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketDispatcherServer is the server API for TicketDispatcher service.
type TicketDispatcherServer interface {
	GetTickets(context.Context, *Empty) (*TicketsInfo, error)
	SetTickets(context.Context, *TicketsInfo) (*Empty, error)
}

func RegisterTicketDispatcherServer(s *grpc.Server, srv TicketDispatcherServer) {
	s.RegisterService(&_TicketDispatcher_serviceDesc, srv)
}

func _TicketDispatcher_GetTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketDispatcherServer).GetTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TicketDispatcher/GetTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketDispatcherServer).GetTickets(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketDispatcher_SetTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketsInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketDispatcherServer).SetTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TicketDispatcher/SetTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketDispatcherServer).SetTickets(ctx, req.(*TicketsInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _TicketDispatcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TicketDispatcher",
	HandlerType: (*TicketDispatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTickets",
			Handler:    _TicketDispatcher_GetTickets_Handler,
		},
		{
			MethodName: "SetTickets",
			Handler:    _TicketDispatcher_SetTickets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "servant_cluster.proto",
}
